### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by naveenduttvyas** [mthenw/frontail#111] opened 2018-02-10 20:17 UTC
installed uing npm command, and when executin below command, getting below error? how to make it work in windows?

frontail C:\Users\Test\Downloads\apache-samples\apache-error_log\error_log\syslog

Error received:

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn tail ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by KidSquid1** [comment] 2019-02-01 20:08
So I'm wondering what magic this guy used to get it up and running on Windows Server 2012?

https://community.openhab.org/t/habpanel-reloaded-modern-theme-skin-custom-widgets/43883/66

**Comment by KidSquid1** [comment] 2019-02-01 22:31
ok, I've installed the resource pack and added the folder to the windows system path and I now have access to TAIL which works as intended...yet I see nothing in the browser window.  I can see the scrolling in the command box but nothing in the browser....see screen cap below.
![tail](https://user-images.githubusercontent.com/28264840/52153237-cff0bf80-263e-11e9-93af-bd0890d03109.png)

**Comment by posipov34** [comment] 2019-07-01 12:08
The problem contains in two parts:
First - the windows resorce pack command tail.exe support either -n or the -f option, but not both. So it it needed to change execution parameters in /lib/tail.js
Second - the bug in the index.js code:
const io = new SocketIO({ path: path.join(urlPath, '/socket.io') });
the path.join(urlPath, '/socket.io') on windows gives a "\\socket.io" string instead of "/socket.io" on linux.
this is the reason why the socket.io is not working.

**Comment by KidSquid1** [comment] 2019-07-02 23:00
@posipov34 

Thank You...Thank You....Thank You..

I made the following changes:

**tail.js**
Line 27 - `    if (process.platform === 'win32') {`
I changed the platform to win32 from the linux flavor that was currently listed.

**index.js**
Line 77 - replaced the entire line with `const io = new SocketIO({ path: path.join(urlPath, '/socket.io').replace(/\\/g,"/") });`

Started up frontail and boom....I now have it working.....

Thanks again for the information!!!

**Comment by upcdy** [comment] 2019-12-12 03:22
@KidSquid1 I tried to change the two file as your instruction and re run frontail c:\temp\syslog , but still got:
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn tail ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn tail',
  path: 'tail',
  spawnargs: [ '-n', 10, '-f', 'c:\\temp\\syslog' ]
}

is there any thing i can do? thanks!

**Comment by Steve-Mcl** [comment] 2020-01-31 17:23
hi @mthenw , it looks like @mojoaxel  did some great work in replacing native tail with nodejs version.  

Have these modifications been merged into your repo?

I ask as I recently installed on windows server (from NPM) and I got same error that the other guys got & had to manually patch `index.js` and `tail.js` files & find a copy of tail for windows.

If your answer is yes, then perhaps NPM needs updating?

Cheers.

**Comment by mojoaxel** [comment] 2020-01-31 19:59
> Have these modifications been merged into your repo?

Sadly the changes have not been merged (#175) but you can use my branch on windows if you need windows support!

**Comment by mthenw** [comment] 2020-02-02 20:28
I'm happy to merge those changes. @mojoaxel please open a new PR.

**Closed** 2020-02-03 11:02 UTC
Labels: accepted, enhancement

**Comment by mthenw** [comment] 2020-02-03 12:23
I published v4.9.0 with Windows support
